sudo: required

language: generic

matrix:
  include:
    - os: osx
      env: COMPILER=4.08.0
    - os: linux
      env: COMPILER=4.02.3
    - os: linux
      env: COMPILER=4.03.0
    - os: linux
      env: COMPILER=4.04.2
    - os: linux
      env: COMPILER=4.05.0
    - os: linux
      env: COMPILER=4.06.1
    - os: linux
      env: COMPILER=4.07.1
    - os: linux
      env: COMPILER=4.08.0
    - os: linux
      env: COMPILER=ocaml-variants.4.09.0+beta1 REPOSITORIES=--repositories=default,beta=git+https://github.com/ocaml/ocaml-beta-repository.git

  allow_failures:
    - env: COMPILER=ocaml-variants.4.09.0+beta1 REPOSITORIES=--repositories=default,beta=git+https://github.com/ocaml/ocaml-beta-repository.git

  fast_finish: true

script: bash -e ./src/util/travis_ci_test.sh

cache:
  directories:
    - $HOME/.opam
    - ./_opam
    - ./_build/default

notifications:
  email:
    on_success: always
    on_failure: always
