sudo: required

language: generic

matrix:
  include:
    - os: linux
      env: OCAML_VERSION=4.02
    - os: linux
      env: OCAML_VERSION=4.03 COVERALLS=yes
    - os: linux
      env: OCAML_VERSION=4.03 BYTECODE_ONLY=yes
    - os: osx
      env: OCAML_VERSION=4.02
    - os: osx
      env: OCAML_VERSION=4.03

script: bash -e ./src/travis_ci_test.sh
