sudo: required
language: generic

matrix:
  include:
    - os: osx
      env: BUCKLESCRIPT=YES SAVE_BINARIES=YES
    - os: linux
      env: BUCKLESCRIPT=YES SAVE_BINARIES=YES
    - os: osx
      env: COMPILER=4.09.0
    - os: linux
      env: COMPILER=4.09.0
    - os: linux
      env: COMPILER=4.08.1 SELF_COVERAGE=YES
    - os: linux
      env: COMPILER=4.07.1 USAGE_TEST=YES
    - os: linux
      env: COMPILER=4.06.1
    - os: linux
      env: COMPILER=4.05.0
    - os: linux
      env: COMPILER=4.04.2
    - os: linux
      env: COMPILER=4.03.0
    - os: linux
      env: COMPILER=4.02.3

  allow_failures:
    - env: COMPILER=4.08.1 SELF_COVERAGE=YES
    - env: COMPILER=4.07.1 USAGE_TEST=YES
    - env: COMPILER=4.06.1
    - env: COMPILER=4.05.0
    - env: COMPILER=4.04.2
    - env: COMPILER=4.03.0

  fast_finish: true

script: bash -e ./test/ci/travis.sh

cache:
  directories:
    - $HOME/.opam
    - ./_opam
    - $HOME/.esy
    - ./test/bucklescript/node_modules
    - ./node_modules
    - ./_cache

notifications:
  email:
    on_success: always
    on_failure: always
